select 
CUTOFF_DATE,
AGREEMENT_ID,
DISBURSAL_DATE,
DISBURSAL_AMOUNT,
DPD_EOM,
RISK_BUCKET,
PRINCIPLE_OUTSTANDING,
STATUS,
MOB,
MAFC_SUB_CATEGORY PRODUCT_TYPE,
NPA_STAGEID,
DPD_GROUP,
STATE_MODEL,
MSCORE_GROUP RISK_SCORE,
SALE_CHANNEL
from RISK.TV_MARKOV_POS_RR tmpr 