select 
CUTOFF_DATE,
AGREEMENT_ID,
DISBURSAL_DATE,
DISBURSAL_AMOUNT,
DPD_EOM,
RISK_BUCKET,
PRINCIPLE_OUTSTANDING,
STATUS,
MOB,
MAFC_SUB_CATEGORY PRODUCT_TYPE,
NPA_STAGEID,
DPD_GROUP,
STATE_MODEL,
CASE WHEN GRADE LIKE '%A%' THEN 'A'
	 WHEN GRADE LIKE '%B%' THEN 'B'
	 WHEN GRADE LIKE '%C%' THEN 'C'
	 ELSE 'D' END 		RISK_SCORE
from RISK.TV_TRI_MARKOV_ETB_RR a