select 
CUTOFF_DATE,
AGREEMENT_ID,
trunc(DISBURSAL_DATE,'MM') DISBURSAL_DATE,
DISBURSAL_AMOUNT,
DPD_EOM,
RISK_BUCKET,
PRINCIPLE_OUTSTANDING,
STATUS,
MOB,
MAFC_SUB_CATEGORY PRODUCT_TYPE,
NPA_STAGEID,
DPD_GROUP,
STATE_MODEL,
CASE WHEN GRADE LIKE '%A%' THEN 'A'
	 WHEN GRADE LIKE '%B%' THEN 'B'
	 WHEN GRADE LIKE '%C%' THEN 'C'
	 ELSE 'D' END 		RISK_SCORE
from RISK.TV_MARKOV_CL_RR a
WHERE a.MAFC_SUB_CATEGORY = 'SALPIL'
and a.CUTOFF_DATE < ADD_MONTHS( trunc (SYSDATE,'MM'),-1)