select 
CUTOFF_DATE,
AGREEMENT_ID,
DISBURSAL_DATE,
DISBURSAL_AMOUNT,
DPD_EOM,
RISK_BUCKET,
PRINCIPLE_OUTSTANDING,
STATUS,
MOB,
PRODUCT_TYPE,
STATE_MODEL,
RISK_SCORE
from TBL_RR_UNSECURED2 a
WHERE a.PRODUCT_TYPE = 'CDLPIL'