select 
CUTOFF_DATE,
AGREEMENT_ID,
DISBURSAL_DATE,
DISBURSAL_AMOUNT,
DPD_EOM,
PRINCIPLE_OUTSTANDING,
STATUS,
MOB,
 PRODUCT_TYPE,
DPD_GROUP,
STATE_MODEL,
RISK_SCORE
from RISK.TBL_RR_UNSECURED a
WHERE 1=1
and a.CUTOFF_DATE < ADD_MONTHS( trunc (SYSDATE,'MM'),-1)